# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c

branches:
 only:
 - master

before_install:
    - brew uninstall xctool && brew install --HEAD xctool

install:
    - gem install cocoapods -v 1.0.1 --no-document

before_script:
    - cd Example
    - pod install

xcode_workspace: NumberMorphView.xcworkspace
xcode_scheme: NumberMorphView-Example
xcode_sdk: iphonesimulator9.3
